// Authentication Constants
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
const GET_TOKEN_NUM = 'GET_TOKEN_NUM';
const GET_TOKEN_NUM_SUCCESS = 'GET_TOKEN_NUM_SUCCESS';
const FETCH_APPOINTMENT_LIST = 'FETCH_APPOINTMENT_LIST';
const FETCH_APPOINTMENT_LIST_SUCCESS = 'FETCH_APPOINTMENT_LIST_SUCCESS';
const GET_DOCTOR_ID = 'GET_DOCTOR_ID';
const GET_DOCTOR_ID_SUCCESS = 'GET_DOCTOR_ID_SUCCESS';
const CREATE_NEW_VISIT = 'CREATE_NEW_VISIT';
const CREATE_NEW_VISIT_SUCCESS = 'CREATE_NEW_VISIT_SUCCESS';
const FETCH_PATIENT_DEMOGRAPHICS = 'FETCH_APATIENT_DEMOGRAPHICS';
const FETCH_PATIENT_DEMOGRAPHICS_SUCCESS = 'FETCH_PATIENT_DEMOGRAPHICS_SUCCESS';
const FETCH_PATIENT_DEMOGRAPHICS_RESET_STATE = 'FETCH_PATIENT_DEMOGRAPHICS_RESET_STATE';
const FETCH_PATIENT_LEGENDS_SUCCESS = 'FETCH_PATIENT_LEGENDS_SUCCESS';
const FETCH_PATIENT_LEGENDS = 'FETCH_PATIENT_LEGENDS';
const FETCH_PRESENTING_COMPLAINTS = 'FETCH_PRESENTING_COMPLAINTS';
const FETCH_PRESENTING_COMPLAINTS_SUCCESS = 'FETCH_PRESENTING_COMPLAINTS_SUCCESS';
const CREATE_PRESENTING_COMPLAINT_ACTION = 'CREATE_PRESENTING_COMPLAINT_ACTION';
const CREATE_PRESENTING_COMPLAINT_SUCCESS = 'CREATE_PRESENTING_COMPLAINT_SUCCESS';
const FETCH_VITALS_DEFINITIONS = 'FETCH_VITALS_DEFINITIONS';
const FETCH_VITALS_DEFINITIONS_SUCCESS = 'FETCH_VITALS_DEFINITIONS_SUCCESS';
const POST_VISIT_VITALS = 'POST_VISIT_VITALS';
const POST_VISIT_VITALS_SUCCESS = 'POST_VISIT_VITALS_SUCCESS';
const FETCH_PATIENT_VITALS = 'FETCH_PATIENT_VITALS';
const FETCH_PATIENT_VITALS_SUCCESS = 'FETCH_PATIENT_VITALS_SUCCESS';
const FETCH_PATIENTS_FOR_DOCTOR_SCREEN = 'FETCH_PATIENTS_FOR_DOCTOR_SCREEN';
const FETCH_PATIENTS_FOR_DOCTOR_SCREEN_SUCCESS = 'FETCH_PATIENTS_FOR_DOCTOR_SCREEN_SUCCESS';
const FETCH_VISIT_VITALS_AND_DEFINITIONS = 'FETCH_VISIT_VITALS_AND_DEFINITIONS';
const FETCH_VISIT_VITALS_AND_DEFINITIONS_SUCCESS = 'FETCH_VISIT_VITALS_AND_DEFINITIONS_SUCCESS';
const FETCH_DIAGNOSTICS_LIST = 'FETCH_DIAGNOSTICS_LIST';
const FETCH_DIAGNOSIS_LIST = 'FETCH_DIAGNOSIS_LIST';
const FETCH_DIAGNOSTICS_LIST_SUCCESS = 'FETCH_DIAGNOSTICS_LIST_SUCCESS';
const FETCH_DIAGNOSIS_LIST_SUCCESS = 'FETCH_DIAGNOSIS_LIST_SUCCESS';
const FETCH_COMMON_DIAGNOSIS_LIST_ACTION = 'FETCH_COMMON_DIAGNOSIS_LIST_ACTION';
const FETCH_COMMON_DIAGNOSIS_LIST_SUCCESS = 'FETCH_COMMON_DIAGNOSIS_LIST_SUCCESS';
const FETCH_COMMON_DIAGNOSTICS_LIST_ACTION = 'FETCH_COMMON_DIAGNOSTICS_LIST_ACTION';
const FETCH_COMMON_DIAGNOSTICS_LIST_SUCCESS = 'FETCH_COMMON_DIAGNOSTICS_LIST_SUCCESS';
const FETCH_DR_PRESENTING_COMPLAINTS_ACTION = 'FETCH_DR_PRESENTING_COMPLAINTS_ACTION';
const FETCH_PRESENTING_COMPLAINTS_DR_SUCCESS = 'FETCH_PRESENTING_COMPLAINTS_DR_SUCCESS';
const FETCH_PRESENTING_COMPLAINTS_ById_DR = 'FETCH_PRESENTING_COMPLAINTS_ById_DR';
const FETCH_PRESENTING_COMPLAINTS_ById_SUCCESS_DR = 'FETCH_PRESENTING_COMPLAINTS_ById_SUCCESS_DR';
const POST_DR_PRESENTING_COMPLAINT_ACTION = 'POST_DR_PRESENTING_COMPLAINT_ACTION';
const POST_PRESENTING_COMPLAINTS_DR_SUCCESS = 'POST_PRESENTING_COMPLAINTS_DR_SUCCESS';
const FETCH_DR_CLINICAL_COMPLAINTS_TEMPLATE_ACTION = 'FETCH_DR_CLINICAL_COMPLAINTS_TEMPLATE_ACTION';
const FETCH_CLINICAL_DETAIL_SUCCESS = 'FETCH_CLINICAL_DETAIL_SUCCESS';
const FETCH_CLINICAL_DETAIL_BYID = 'FETCH_CLINICAL_DETAIL_ById';
const FETCH_CLINICAL_DETAIL_BYID_SUCCESS = 'FETCH_CLINICAL_DETAIL_ById_SUCCESS';
const POST_DR_CLINICAL_TEMPLATES_ACTION = 'POST_DR_CLINICAL_TEMPLATES_ACTION';
const POST_CLINICAL_DETAILS_SUCCESS = 'POST_CLINICAL_DETAILS_SUCCESS';
const FETCH_DIAGNOSIS_LIST_DR = 'FETCH_DIAGNOSIS_LIST_DR';
const FETCH_DIAGNOSIS_LIST_DR_SUCCESS = 'FETCH_DIAGNOSIS_LIST_DR_SUCCESS';
const FETCH_DIAGNOSIS_TEMPLATES_LIST_ACTION = 'FETCH_DIAGNOSIS_TEMPLATES_LIST_ACTION';
const FETCH_DIAGNOSIS_TEMPLATES_LIST_SUCCESS = 'FETCH_DIAGNOSIS_TEMPLATES_LIST_SUCCESS';
const POST_DIAGNOSIS_TEMPLATES_LIST_ACTION = 'POST_DIAGNOSIS_TEMPLATES_LIST_ACTION';
const POST_ALLERGY_TEMPLATES_LIST_ACTION = 'POST_ALLERGY_TEMPLATES_LIST_ACTION ';
const POST_DIAGNOSIS_TEMPLATES_LIST_SUCCESS = 'POST_DIAGNOSIS_TEMPLATES_LIST_SUCCESS';
const POST_ALLERGY_TEMPLATES_LIST_SUCCESS = 'POST_ALLERGY_TEMPLATES_LIST_SUCCESS';
const FETCH_DIAGNOSTICS_TEMPLATES_LIST_ACTION = 'FETCH_DIAGNOSTICS_TEMPLATES_LIST_ACTION';
const FETCH_DIAGNOSTICS_TEMPLATES_LIST_SUCCESS = 'FETCH_DIAGNOSTICS_TEMPLATES_LIST_SUCCESS';
const POST_DIAGNOSTICS_TEMPLATES_LIST_ACTION = 'POST_DIAGNOSTICS_TEMPLATES_LIST_ACTION';
const POST_DIAGNOSTICS_TEMPLATES_LIST_SUCCESS = 'POST_DIAGNOSTICS_TEMPLATES_LIST_SUCCESS';
const FETCH_PATIENT_PREVIOUS_VISITS_LIST_ACTION = 'FETCH_PATIENT_PREVIOUS_VISITS_LIST_ACTION';
const FETCH_PATIENT_PREVIOUS_VISITS_LIST_SUCCESS = 'FETCH_PATIENT_PREVIOUS_VISITS_LIST_SUCCESS';
const FETCH_ALL_MEDICINES_LIST_ACTION = 'FETCH_ALL_MEDICINES_LIST_ACTION';
const FETCH_ALL_MEDICINES_LIST_SUCCESS = 'FETCH_ALL_MEDICINES_LIST_SUCCESS';
const FETCH_COMMON_MEDICINES_LIST_ACTION = 'FETCH_COMMON_MEDICINES_LIST_ACTION';
const FETCH_COMMON_MEDICINES_LIST_SUCCESS = 'FETCH_COMMON_MEDICINES_LIST_SUCCESS';
const FETCH_MEDICINES_TEMPLATES_LIST_ACTION = 'FETCH_MEDICINES_TEMPLATES_LIST_ACTION';
const FETCH_MEDICINES_TEMPLATES_LIST_SUCCESS = 'FETCH_MEDICINES_TEMPLATES_LIST_SUCCESS';
const POST_MEDICINES_TEMPLATE_ACTION = 'POST_MEDICINES_TEMPLATE_ACTION';
const POST_MEDICINES_TEMPLATE_SUCCESS = 'POST_MEDICINES_TEMPLATE_SUCCESS';
const FETCH_SEARCHED_DIAGNOSIS_ACTION = 'FETCH_SEARCHED_DIAGNOSIS_ACTION';
const FETCH_SEARCHED_DIAGNOSIS_SUCCESS = 'FETCH_SEARCHED_DIAGNOSIS_SUCCESS';
const FETCH_SEARCHED_DIAGNOSTICS_ACTION = 'FETCH_SEARCHED_DIAGNOSIS_SUCCESS';
const FETCH_SEARCHED_DIAGNOSTICS_SUCCESS = 'FETCH_SEARCHED_DIAGNOSTICS_SUCCESS';
const FETCH_SEARCHED_MEDICINES_ACTION = 'FETCH_SEARCHED_MEDICINES_ACTION';
const FETCH_SEARCHED_MEDICINES_SUCCESS = 'FETCH_SEARCHED_MEDICINES_SUCCESS';

const FETCH_BRANDS_ALLERGIES_LIST_ACTION = 'FETCH_BRANDS_ALLERGIES_LIST_ACTION';
const FETCH_BRANDS_ALLERGIES_LIST_SUCCESS = 'FETCH_BRANDS_ALLERGIES_LIST_SUCCESS';

const FETCH_GENERIC_ALLERGIES_LIST_ACTION = 'FETCH_GENERIC_ALLERGIES_LIST_ACTION';
const FETCH_GENERIC_ALLERGIES_LIST_SUCCESS = 'FETCH_GENERIC_ALLERGIES_LIST_SUCCESS';

const FETCH_DOCTOR_ALLERGIES_TEMPLATES_LIST_ACTION = 'FETCH_DOCTOR_ALLERGIES_TEMPLATES_LIST_ACTION';
const FETCH_DOCTOR_ALLERGIES_TEMPLATES_LIST_SUCCESS = 'FETCH_DOCTOR_ALLERGIES_TEMPLATES_LIST_SUCCESS';
const SAVE_ALLERGIES_TO_REDUX = 'SAVE_ALLERGIES_TO_REDUX';
const SAVE_DIAGNOSIS_TO_REDUX = 'SAVE_DIAGNOSIS_TO_REDUX';
const SAVE_DIAGNOSTICS_TO_REDUX = 'SAVE_DIAGNOSTICS_TO_REDUX';
const SAVE_MEDICATION_TO_REDUX = 'SAVE_MEDICATION_TO_REDUX';
const SAVE_PRESENTING_COMPLAINT_TO_REDUX = 'SAVE_PRESENTING_COMPLAINT_TO_REDUX';
const SAVE_CLINICAL_DETAILS_TO_REDUX = 'SAVE_CLINICAL_DETAILS_TO_REDUX';
const SAVE_IMPRESSION_TO_REDUX = 'SAVE_IMPRESSION_TO_REDUX';
const SAVE_MANAGEMENT_PLAN_TO_REDUX = 'SAVE_MANAGEMENT_PLAN_TO_REDUX';
const SAVE_PHYSICAL_EXAMINATION_TO_REDUX = 'SAVE_PHYSICAL_EXAMINATION_TO_REDUX';
const SAVE_VITALS_TO_REDUX = 'SAVE_VITALS_TO_REDUX';
const SELECTED_PATIENT = 'SELECTED_PATIENT';
const SELECTED_DATE = 'SELECTED_DATE';
const SET_PATIENT_DEMOGRAPHICS_EMPTY_OBJECT = 'SET_PATIENT_DEMOGRAPHICS_EMPTY_OBJECT';

export {
  USER_LOGIN,
  USER_LOGIN_SUCCESS,
  USER_LOGOUT,
  USER_LOGOUT_SUCCESS,
  GET_TOKEN_NUM,
  GET_TOKEN_NUM_SUCCESS,
  FETCH_APPOINTMENT_LIST,
  FETCH_APPOINTMENT_LIST_SUCCESS,
  GET_DOCTOR_ID,
  GET_DOCTOR_ID_SUCCESS,
  CREATE_NEW_VISIT,
  CREATE_NEW_VISIT_SUCCESS,
  FETCH_PATIENT_DEMOGRAPHICS,
  FETCH_PATIENT_DEMOGRAPHICS_SUCCESS,
  FETCH_PATIENT_DEMOGRAPHICS_RESET_STATE,
  FETCH_PATIENT_LEGENDS,
  FETCH_PATIENT_LEGENDS_SUCCESS,
  FETCH_PRESENTING_COMPLAINTS,
  FETCH_PRESENTING_COMPLAINTS_SUCCESS,
  CREATE_PRESENTING_COMPLAINT_ACTION,
  CREATE_PRESENTING_COMPLAINT_SUCCESS,
  FETCH_VITALS_DEFINITIONS,
  FETCH_VITALS_DEFINITIONS_SUCCESS,
  POST_VISIT_VITALS,
  POST_VISIT_VITALS_SUCCESS,
  FETCH_PATIENT_VITALS,
  FETCH_PATIENT_VITALS_SUCCESS,
  FETCH_PATIENTS_FOR_DOCTOR_SCREEN,
  FETCH_PATIENTS_FOR_DOCTOR_SCREEN_SUCCESS,
  FETCH_VISIT_VITALS_AND_DEFINITIONS,
  FETCH_VISIT_VITALS_AND_DEFINITIONS_SUCCESS,
  FETCH_DIAGNOSTICS_LIST,
  FETCH_DIAGNOSIS_LIST,
  FETCH_DIAGNOSTICS_LIST_SUCCESS,
  FETCH_DIAGNOSIS_LIST_SUCCESS,
  FETCH_COMMON_DIAGNOSIS_LIST_ACTION,
  FETCH_COMMON_DIAGNOSIS_LIST_SUCCESS,
  FETCH_COMMON_DIAGNOSTICS_LIST_ACTION,
  FETCH_COMMON_DIAGNOSTICS_LIST_SUCCESS,
  FETCH_PRESENTING_COMPLAINTS_DR_SUCCESS,
  FETCH_DR_PRESENTING_COMPLAINTS_ACTION,
  FETCH_PRESENTING_COMPLAINTS_ById_DR,
  FETCH_PRESENTING_COMPLAINTS_ById_SUCCESS_DR,
  POST_DR_PRESENTING_COMPLAINT_ACTION,
  POST_PRESENTING_COMPLAINTS_DR_SUCCESS,
  FETCH_DR_CLINICAL_COMPLAINTS_TEMPLATE_ACTION,
  FETCH_CLINICAL_DETAIL_SUCCESS,
  FETCH_CLINICAL_DETAIL_BYID,
  FETCH_CLINICAL_DETAIL_BYID_SUCCESS,
  POST_DR_CLINICAL_TEMPLATES_ACTION,
  POST_CLINICAL_DETAILS_SUCCESS,
  FETCH_DIAGNOSIS_LIST_DR,
  FETCH_DIAGNOSIS_LIST_DR_SUCCESS,
  FETCH_DIAGNOSIS_TEMPLATES_LIST_ACTION,
  FETCH_DIAGNOSIS_TEMPLATES_LIST_SUCCESS,
  POST_DIAGNOSIS_TEMPLATES_LIST_ACTION,
  POST_ALLERGY_TEMPLATES_LIST_ACTION,
  POST_DIAGNOSIS_TEMPLATES_LIST_SUCCESS,
  POST_ALLERGY_TEMPLATES_LIST_SUCCESS,
  FETCH_DIAGNOSTICS_TEMPLATES_LIST_ACTION,
  FETCH_DIAGNOSTICS_TEMPLATES_LIST_SUCCESS,
  POST_DIAGNOSTICS_TEMPLATES_LIST_ACTION,
  POST_DIAGNOSTICS_TEMPLATES_LIST_SUCCESS,
  FETCH_PATIENT_PREVIOUS_VISITS_LIST_ACTION,
  FETCH_PATIENT_PREVIOUS_VISITS_LIST_SUCCESS,
  FETCH_ALL_MEDICINES_LIST_ACTION,
  FETCH_ALL_MEDICINES_LIST_SUCCESS,
  FETCH_COMMON_MEDICINES_LIST_ACTION,
  FETCH_COMMON_MEDICINES_LIST_SUCCESS,
  FETCH_MEDICINES_TEMPLATES_LIST_ACTION,
  FETCH_MEDICINES_TEMPLATES_LIST_SUCCESS,
  POST_MEDICINES_TEMPLATE_ACTION,
  POST_MEDICINES_TEMPLATE_SUCCESS,
  FETCH_SEARCHED_DIAGNOSIS_ACTION,
  FETCH_SEARCHED_DIAGNOSIS_SUCCESS,
  FETCH_SEARCHED_DIAGNOSTICS_ACTION,
  FETCH_SEARCHED_DIAGNOSTICS_SUCCESS,
  FETCH_SEARCHED_MEDICINES_ACTION,
  FETCH_SEARCHED_MEDICINES_SUCCESS,
  FETCH_BRANDS_ALLERGIES_LIST_ACTION,
  FETCH_BRANDS_ALLERGIES_LIST_SUCCESS,
  FETCH_GENERIC_ALLERGIES_LIST_ACTION,
  FETCH_GENERIC_ALLERGIES_LIST_SUCCESS,
  FETCH_DOCTOR_ALLERGIES_TEMPLATES_LIST_ACTION,
  FETCH_DOCTOR_ALLERGIES_TEMPLATES_LIST_SUCCESS,
  SAVE_ALLERGIES_TO_REDUX,
  SAVE_DIAGNOSIS_TO_REDUX,
  SAVE_DIAGNOSTICS_TO_REDUX,
  SAVE_MEDICATION_TO_REDUX,
  SAVE_PRESENTING_COMPLAINT_TO_REDUX,
  SAVE_CLINICAL_DETAILS_TO_REDUX,
  SAVE_IMPRESSION_TO_REDUX,
  SAVE_MANAGEMENT_PLAN_TO_REDUX,
  SAVE_PHYSICAL_EXAMINATION_TO_REDUX,
  SAVE_VITALS_TO_REDUX,
  SELECTED_PATIENT,
  SELECTED_DATE,
  SET_PATIENT_DEMOGRAPHICS_EMPTY_OBJECT
};
