// Authentication Constants
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';


export {
  USER_LOGIN,
  USER_LOGIN_SUCCESS,
  USER_LOGOUT,
  USER_LOGOUT_SUCCESS,
};
